### ISSUE TITLE
VS 2013 - MSVCP100D.dll is missing...

### ISSUE THREAD

**Issue by JamesHagerman** [jimbo00000/RiftSkeleton#3]
After finally grabbing all of the dependencies and double checking the project settings, I started getting this error. I'm using VS 2013, I'm compiling in Debug mode, and I can't find a copy of MSVCP100D.dll anywhere on my machine.

If I try building the Release version, I get a LOT of errors coming from the internals of the libraries themselves...

I'll keep digging but is there any chance you could try getting this to build with VS 2013? Maybe something's changed between versions of VS?

**Comment by JamesHagerman** [comment]
It's not, no.

There are different versions of the debug DLLs for different versions of Visual Studio, right?

So somewhere there is a reference to the msvcp100d.dll file even though the 2013 version of Visual Studio is not actually pulling that DLL down from the Microsoft Symbols Server. It's pulled down msvcp110d.dll and msvcp120d.dll because I guess it knows about those versions... and it's pulled down msvcp100.dll (without debugging symbols)... but I can't figure out a way to get my hands on the msvcp100d.dll that this program is referencing because it's non-distributable (says Microsoft).

I'll keep digging but I found some other code to work off of in the meantime.

**Comment by jimbo00000** [comment]
I found a couple of likely culprits in CMakeLists.txt, lines 41 and 62. Both GLFW3 and the OVR SDK link to specific versions of Visual Studio libraries in their compiled .lib files. You could try changing the OVR one to point to LibOVR/Lib/Win32/VS2013, and for the GLFW one download the 3.0.4 Win32 binary build that includes a lib-msvc120 and point to that.

I've been using 2010 Express because I vaguely remember Oculus mentioning saying they "standardized" on it. I probably let some 2010-isms sneak into the Windows build path accidentally - hopefully they can be properly fixed with some logic in CMakeLists.txt and RiftSkeleton can build without modification on as many systems as possible.

**Comment by jimbo00000** [comment]
Try the latest as of 4548b25a83e82a717debf416eae3c626c4e9bb34, I've added logic to CMakeLists.txt to link to the correct libraries for your VS version.
